allowBuilds:
  esbuild: true
  "@google/genai": true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@assistant-ui/core@0.3.17'
  - '@assistant-ui/react@0.15.18'
  - '@assistant-ui/store@0.3.12'
  - '@assistant-ui/tap@0.9.16'
  - assistant-cloud@0.1.43
  - assistant-stream@0.3.41
  - safe-content-frame@0.0.29
patchedDependencies:
  '@assistant-ui/react-pi@0.0.20': patches/@assistant-ui__react-pi@0.0.20.patch
